# Generated by Django 4.2.18 on 2025-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0556_add_execution_order_to_hog_functions"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="api_query_rate_limit",
            field=models.CharField(blank=True, help_text="API rate limit", max_length=32, null=True),
        ),
    ]
